[WIP] CI improvements
offspot/base-image pull request #25
Opened 2022-06-06 15:08 UTC by kelson42

2022-06-06 15:24 UTC, kelson42 commented
@rgaudin I believe to have configured the `workflow_dispatch` properly... but somehow it does not appear on the UI and I was not able to test it properly.

2022-06-06 16:11 UTC, rgaudin commented
> @rgaudin I believe to have configured the `workflow_dispatch` properly... but somehow it does not appear on the UI and I was not able to test it properly.

Needs to be on main branch

2022-06-06 16:49 UTC, kelson42 commented
@rgaudin Can I merge then?

2022-06-07 08:29 UTC, rgaudin requested changes
See inline comments

2022-06-07 15:51 UTC, kelson42 commented on .github/workflows/build-and-upload.yml
> +        default: 1
fixed in latest commit

2022-06-07 15:53 UTC, kelson42 commented on .github/workflows/build-and-upload.yml
> +        if: ${{ github.event.inputs.publish-to-s3 }}
fixed in latest commit

2022-06-07 15:57 UTC, rgaudin approved these changes
LGTM

2022-06-07 16:39 UTC, merged